### ISSUE TITLE
Update Readme

### ISSUE THREAD

**Issue by Aniruddha-Shriwant** [Aniruddha-Shriwant/Budgety#5]
Update the `readme.md` file which will represent the app features also include the languages and any tech stack used

**Comment by OmkarPh** [comment]
Hi @Aniruddha-Shriwant 
I have created a good README, have a look and add/modify anything if you want

I'll send the PR in couple of minutes.

**Comment by Aniruddha-Shriwant** [comment]
Great thanks will merge #6  soon
